blank_issues_enabled: false
contact_links:
  - name: Questions and discussion
    url: https://github.com/robmoteka/laneflow/discussions
    about: Use GitHub Discussions for general questions about LaneFlow.
